-- Handshake.sh — initial schema migration
--
-- NOTE: hand-authored, not generated by `prisma migrate diff`, because this
-- environment has no network access to Prisma's engine binaries. Run
-- `npx prisma validate` and `npx prisma migrate dev` yourself before trusting
-- this against a real database — treat this file as a reviewable draft, not
-- a verified artifact, until you've done that.

-- CreateTable
CREATE TABLE "users" (
    "id" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "fullName" TEXT NOT NULL,
    "college" TEXT NOT NULL,
    "department" TEXT,
    "year" INTEGER,
    "email" TEXT NOT NULL,
    "profilePhotoUrl" TEXT,
    "handshakeCount" INTEGER NOT NULL DEFAULT 0,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "isAdmin" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "handshake_codes" (
    "id" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "usedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "handshake_codes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "handshakes" (
    "id" TEXT NOT NULL,
    "initiatorId" TEXT NOT NULL,
    "responderId" TEXT NOT NULL,
    "userLowId" TEXT NOT NULL,
    "userHighId" TEXT NOT NULL,
    "codeId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "handshakes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "admin_actions" (
    "id" TEXT NOT NULL,
    "adminId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "targetUserId" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "admin_actions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_username_key" ON "users"("username");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE INDEX "users_handshakeCount_idx" ON "users"("handshakeCount");

-- CreateIndex
CREATE INDEX "handshake_codes_ownerId_usedAt_idx" ON "handshake_codes"("ownerId", "usedAt");

-- CreateIndex
CREATE INDEX "handshake_codes_code_usedAt_idx" ON "handshake_codes"("code", "usedAt");

-- CreateIndex
CREATE UNIQUE INDEX "handshakes_codeId_key" ON "handshakes"("codeId");

-- CreateIndex
CREATE UNIQUE INDEX "handshakes_userLowId_userHighId_key" ON "handshakes"("userLowId", "userHighId");

-- AddForeignKey
ALTER TABLE "handshake_codes" ADD CONSTRAINT "handshake_codes_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "handshakes" ADD CONSTRAINT "handshakes_initiatorId_fkey" FOREIGN KEY ("initiatorId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "handshakes" ADD CONSTRAINT "handshakes_responderId_fkey" FOREIGN KEY ("responderId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "handshakes" ADD CONSTRAINT "handshakes_codeId_fkey" FOREIGN KEY ("codeId") REFERENCES "handshake_codes"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "admin_actions" ADD CONSTRAINT "admin_actions_adminId_fkey" FOREIGN KEY ("adminId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
